### PR TITLE
Send logs over tls

### PR DESCRIPTION
**Pull request by StephenHynes7**
Should send over tls versus plain text.

### CODE REVIEW

**Comment by StephenHynes7** [comment]
@bsphere can you take a look?

**Comment by bsphere** [comment]
Build ia failing, please fix..

**Comment by jcftang-r7** [comment]
This is an easy fix...

```
1z [jtang:~/sandbox/le_go] [sandbox] use-secure-port(+1/-1)* 11s ± git diff
diff --git a/le.go b/le.go
index 596db7d..3d80081 100644
--- a/le.go
+++ b/le.go
@@ -59,7 +59,7 @@ func (logger *Logger) Close() error {
 // Opens a TCP connection to logentries.com
 func (logger *Logger) openConnection() error {
        config := tls.Config{}
-       conn, err := tls.Dial("tcp", "data.logentries.com:443")
+       conn, err := tls.Dial("tcp", "data.logentries.com:443", &config)
        if err != nil {
                return err
        }
```

**Comment by StephenHynes7** [comment]
Rebuilding now.

**Comment by StephenHynes7** [comment]
@bsphere should be good now.

**Comment by caarlos0** [comment]
Very nice!

**Pull request merged**
